# Generated by Django 4.1.4 on 2022-12-19 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0004_remove_choice_question_alter_course_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(upload_to='uploads/course_img/'),
        ),
    ]
